{
 "title": "New dashboard",
 "time": { "from": "2025-08-20T00:00:00.000Z", "to": "2025-08-23T00:00:00.000Z" },
 "panels": [
  {
   "title": "Number of Active URLS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS active_urls\r\nFROM url_mapping\r\nWHERE expires_at > NOW();"
    }
   ]
  },
  {
   "title": "Total Clicks per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE(timestamp) AS day,\r\n  COUNT(*) AS total_clicks\r\nFROM url_click_analytics\r\nGROUP BY day\r\nORDER BY day;"
    }
   ]
  },
  {
   "title": "Total Custom Links",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  is_custom,\r\n  COUNT(*) AS count\r\nFROM url_mapping\r\nGROUP BY is_custom;\r\n"
    },
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT city, country, COUNT(*) AS clicks\r\nFROM url_click_analytics\r\nGROUP BY city, country\r\nORDER BY clicks DESC\r\nLIMIT 15;"
    },
    {}
   ]
  },
  {
   "title": "Average Clicks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(click_count) AS avg_clicks\r\nFROM url_mapping;\r\n"
    },
    {}
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    },
    { "rawSql": "\r\n" },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    },
    {}
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  browser,\r\n  COUNT(*) AS clicks\r\nFROM url_click_analytics\r\nGROUP BY browser\r\nORDER BY clicks DESC\r\nLIMIT 10;\r\n"
    },
    {}
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "\r\n\r\n" },
    {
     "rawSql": "SELECT short_code, original_url, click_count\r\nFROM url_mapping\r\nORDER BY click_count DESC\r\nLIMIT 10;\r\n\r\n"
    },
    {
     "rawSql": "SELECT\r\n  DATE(created_at) AS day,\r\n  COUNT(*) AS new_short_urls\r\nFROM url_mapping\r\nGROUP BY day\r\nORDER BY day;\r\n"
    },
    {}
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  country,\r\n  COUNT(*) AS clicks\r\nFROM url_click_analytics\r\nGROUP BY country\r\nORDER BY clicks DESC\r\nLIMIT 10;\r\n"
    },
    {}
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATE(timestamp) AS day,\r\n  COUNT(*) AS total_clicks\r\nFROM url_click_analytics\r\nGROUP BY day\r\nORDER BY day;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  country,\r\n  COUNT(*) AS clicks\r\nFROM url_click_analytics\r\nGROUP BY country\r\nORDER BY clicks DESC\r\nLIMIT 10;\r\n"
    }
   ]
  }
 ]
}