services:
  app:
    build: .
    container_name: snaplink-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/snaplink
      DATABASE_USERNAME: snaplink
      DATABASE_PASSWORD: snaplink
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_TIMEOUT: 2000ms
      REDIS_HEALTH_ENABLED: "false"
      KAFKA_BOOTSTRAP_SERVERS: snaplink-kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - snaplink-net

  postgres:
    image: postgres:16
    container_name: snaplink-postgres
    environment:
      POSTGRES_DB: snaplink
      POSTGRES_USER: snaplink
      POSTGRES_PASSWORD: snaplink
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - snaplink-net

  redis:
    image: redis:7-alpine
    container_name: snaplink-redis
    ports:
      - "6379:6379"
    networks:
      - snaplink-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: snaplink-kafka
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@snaplink-kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://snaplink-kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    ports:
      - "9092:9092"
    networks:
      snaplink-net:
        aliases:
          - kafka
          - snaplink-kafka

volumes:
  postgres_data:

networks:
  snaplink-net:
