services:
  - type: web
    name: url-shortener-app
    env: docker
    repo: https://github.com/vaibhavgala262/Snaplink.git
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: url-shortener-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: url-shortener-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: url-shortener-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: lite
    healthCheckPath: /

databases:
  - name: url-shortener-db
    databaseName: url_shortener
    user: url_shortener_user
    plan: free