services:
  - type: web
    name: url-shortener-app
    env: docker
    repo: https://github.com/vaibhavgala262/Snaplink.git
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: url-shortener-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: url-shortener-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: url-shortener-db
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: url-shortener-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: url-shortener-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: lite
    healthCheckPath: /

databases:
  - name: url-shortener-db
    databaseName: url_shortener
    user: url_shortener_user
    plan: free