sonar.projectKey=vaibhavGala262_SnapLink
sonar.organization=vaibhavgala262

sonar.projectName=Snaplink

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.java.source=23

sonar.exclusions=target/**,src/main/resources/**,**/GeoLite2-City.mmdb
sonar.coverage.exclusions=**/config/**,**/UrlShortnerApplication.java
